dimension_id: service
business_name: 서비스

mappings:
  - table: notification_index
    column: index
    pattern:
      prefix: SV#
      extract: suffix

joins:
  - notification
  - notification_status
  - notification_channels
  - recipient